### PR TITLE
Add vcpkg badge

### PR DESCRIPTION
**Pull request by oold**

### CODE REVIEW

**Review by ricab — COMMENTED** [review]
Cool, thank you for adding this to vcpkg! 

Could the badge also link to a view of the package online, somewhere reliable? It isn't showing up in https://vcpkg.io/en/packages.html for me, so maybe https://vcpkg.link/ports/scope-guard ?

**Comment by oold** [comment]
I'm somewhat surprised it's not showing up on the official package index. I can link to the other site, though.

**Comment by ricab** [comment]
I imagine it's a matter of time, maybe they only update every so often. We can update the link if it becomes available.

**Review by ricab — APPROVED** [review]
Cool, thanks again!

**Pull request merged**
